
-- Create scenic_routes table
CREATE TABLE IF NOT EXISTS scenic_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    cover_image VARCHAR(255),
    description TEXT,
    days SMALLINT,
    price DECIMAL(10, 2) DEFAULT 0.00,
    tags JSONB DEFAULT '[]'::jsonb,
    location VARCHAR(255),
    difficulty VARCHAR(50),
    distance VARCHAR(50),
    duration VARCHAR(50),
    altitude VARCHAR(50),
    best_season VARCHAR(100),
    gear JSONB DEFAULT '[]'::jsonb,
    itinerary JSONB DEFAULT '[]'::jsonb,
    category VARCHAR(50),
    scenic_spots JSONB DEFAULT '[]'::jsonb,
    full_desc TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE scenic_routes ENABLE ROW LEVEL SECURITY;

-- Create Policy for Public Read Access
CREATE POLICY "Enable read access for all users" ON "public"."scenic_routes"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- Create Policy for Service Role (Insert/Update/Delete)
-- Note: Service role bypasses RLS, but explicit policy helps clarity
CREATE POLICY "Enable insert for authenticated users only" ON "public"."scenic_routes"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only" ON "public"."scenic_routes"
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Enable delete for authenticated users only" ON "public"."scenic_routes"
AS PERMISSIVE FOR DELETE
TO authenticated
USING (true);
